export const products = [
  {
    id: "bot",
    title: "Rust Rocket Bot",
    subtitle: "Execute trades in Telegram at sub-second latency – full key ownership, no custodial risk.",
    href: "https://t.me/RustRocketBot",
    ctaText: "Open in Telegram",
    icons: ["/icons/telegram.png", "/icons/solana.png"],
    image: "/features/rust-rocket.png",
    alt: "Rust Rocket trading bot terminal",
  },
  {
    id: "dex",
    title: "Web DEX",
    subtitle: "A full-featured, non-custodial web interface for advanced trading, analytics, and liquidity provision.",
    href: "/products/dex",
    ctaText: "Coming soon",
    icons: ["/icons/raydium.png", "/icons/solana.png"],
    image: "/features/web-dex.png",
    alt: "Raydium swap interface on VortexChain Web DEX",
  },
  {
    id: "extension",
    title: "Chrome Extension",
    subtitle: "Trade directly from any website, snipe new token launches, and manage your portfolio on the fly.",
    href: "/products/extension",
    ctaText: "Coming soon",
    icons: ["/icons/chrome.png", "/icons/solana.png"],
    image: "/features/chrome-ext.png",
    alt: "VortexChain Chrome extension popup",
  },
  {
    id: "leaderboard",
    title: "Leaderboard",
    subtitle: "Compete with other traders based on PnL, track top wallets, and earn exclusive rewards for performance.",
    href: "/products/leaderboard",
    ctaText: "Coming soon",
    icons: ["/icons/solana.png"],
    image: "/features/leaderboard.png",
    alt: "VortexChain trading leaderboard showing top users and their profits",
  },
  {
    id: "launchpad",
    title: "Launchpad (Beta)",
    subtitle: "List your Sol-meme token in 24 h – MiCA-ready White-Paper workflow.",
    href: "/products/launchpad",
    ctaText: "Coming soon",
    icons: ["/icons/solana.png"],
    image: "/features/launchpad.png",
    badge: "0.2% fee",
    isNew: true,
    alt: "VortexChain token launchpad interface",
  },
]
