export const products = [
  {
    id: "bot",
    slug: "bot",
    title: "Rust Rocket Bot",
    name: "Rust Rocket Bot",
    subtitle: "Execute trades in Telegram at sub-second latency – full key ownership, no custodial risk.",
    description: "Ultra-fast Solana trading bot with <0.4s execution. Snipe meme coins, copy profitable wallets, non-custodial MPC wallet.",
    href: "/products/bot",
    ctaText: "Learn More",
    icons: ["/RR_favicon-32x32.png", "/icons/solana.png"],
    image: "/Logo_Main_RR.jpg",
    alt: "Rust Rocket Bot Logo",
    category: "Trading Bot",
    keywords: ["telegram bot", "solana trading", "meme coin sniper", "copy trading", "rust rocket"],
  },
  {
    id: "dex",
    slug: "dex",
    title: "Web DEX",
    name: "Web DEX",
    subtitle: "A full-featured, non-custodial web interface for advanced trading, analytics, and liquidity provision.",
    description: "Advanced Solana DEX with real-time analytics, liquidity pools, and professional trading tools.",
    href: "/products/dex",
    ctaText: "Coming soon",
    icons: ["/icons/raydium.png", "/icons/solana.png"],
    image: "/features/web-dex.png",
    alt: "Raydium swap interface on Vortex Group Web DEX",
    category: "DEX Platform",
    keywords: ["solana dex", "web trading", "liquidity pools", "analytics"],
  },
  {
    id: "extension",
    slug: "extension",
    title: "Chrome Extension",
    name: "Chrome Extension",
    subtitle: "Trade directly from any website, snipe new token launches, and manage your portfolio on the fly.",
    description: "Browser extension for seamless Solana trading, token sniping, and portfolio management.",
    href: "/products/extension",
    ctaText: "Coming soon",
    icons: ["/icons/chrome.png", "/icons/solana.png"],
    image: "/features/chrome-ext.png",
    alt: "Vortex Group Chrome extension popup",
    category: "Browser Extension",
    keywords: ["chrome extension", "browser trading", "token sniper", "portfolio"],
  },
  {
    id: "leaderboard",
    slug: "leaderboard",
    title: "Leaderboard",
    name: "Leaderboard",
    subtitle: "Compete with other traders based on PnL, track top wallets, and earn exclusive rewards for performance.",
    description: "Trading competition platform with PnL tracking, wallet rankings, and performance rewards.",
    href: "/products/leaderboard",
    ctaText: "Coming soon",
    icons: ["/icons/solana.png"],
    image: "/features/leaderboard.png",
    alt: "Vortex Group trading leaderboard showing top users and their profits",
    category: "Competition",
    keywords: ["trading competition", "leaderboard", "pnl tracking", "rewards"],
  },
  {
    id: "launchpad",
    slug: "launchpad",
    title: "Launchpad (Beta)",
    name: "Launchpad",
    subtitle: "List your Sol-meme token in 24 h – MiCA-ready White-Paper workflow.",
    description: "Fast token launch platform with 24-hour deployment and MiCA compliance automation.",
    href: "/products/launchpad",
    ctaText: "Coming soon",
    icons: ["/icons/solana.png"],
    image: "/placeholder-qxyp0.png",
    alt: "Vortex Group token launchpad interface",
    category: "Launchpad",
    keywords: ["token launch", "mica compliance", "solana launchpad", "meme coin"],
    badge: "0.2% fee",
  },
]
